# tasks file
---
- include_task: wp-cli.yml
  tags:
    - configuration
    - wordpress
    - wordpress-wp-cli

- include_task: core.yml
  tags:
    - configuration
    - wordpress
    - wordpress-core

- include_task: configure.yml
  tags:
    - configuration
    - wordpress
    - wordpress-configure

- include_task: wp-cron.yml
  tags:
    - configuration
    - wordpress
    - wordpress-wp-cron

- include_task: themes.yml
  tags:
    - configuration
    - wordpress
    - wordpress-themes

- include_task: plugins.yml
  tags:
    - configuration
    - wordpress
    - wordpress-plugins

- include_task: users.yml
  tags:
    - configuration
    - wordpress
    - wordpress-users

- include_task: options.yml
  tags:
    - configuration
    - wordpress
    - wordpress-options

- include_task: queries.yml
  tags:
    - configuration
    - wordpress
    - wordpress-queries

- include_task: chown.yml
  tags:
    - configuration
    - wordpress
    - wordpress-chown
