---

- name: Install Wordpress on server
  hosts: localhost
  connection: local

  roles:
    - ansible-role-apache-master
    - ansible-role-php-master
    - ansible-role-mysql-master
    - ansible-wordpress-master
    - jagoanhosting.wordpress
  vars:
    # Required Variable
    wordpress_theme: "portal_berita_olahraga"
    wordpress_domain: "vm.spearcrow.com"
    wordpress_domain_protocol: "http://"
    wordpress_fqdndomain: "{{ wordpress_domain_protocol }}{{ wordpress_domain }}"
    wordpress_install_dir: "/var/www/vmspearcrowcom"
    wordpress_db_name: "wp_{{ wordpress_theme }}"
    wordpress_user_name: "user_{{ wordpress_theme }}"
    wordpress_user_password: "Jagoan123"
    wordpress_blog_title: "Wordpress Title"
    wordpress_blog_description: "Wordpress Description"
    wordpress_blog_admin_name: "admin"
    wordpress_blog_admin_email: "root@localhost.localdomain"
    wordpress_blog_admin_password: "Jagoan123"
    # Basic Variable from Ansible Role
    php_packages_extra:
      - php-curl
      - php-imagick
      - php-gd
    apache_vhosts_filename: "000-default.conf"
    mysql_root_password: Jago4n123@
    mysql_databases:
      - name: "{{ wordpress_db_name }}"
        encoding: latin1
        collation: latin1_general_ci
    mysql_users:
      - name: "{{ wordpress_user_name }}"
        host: "%"
        password: "{{ wordpress_user_password }}"
        priv: "{{ wordpress_db_name }}.*:ALL"
    apache_vhosts:
      - { servername: "{{ wordpress_domain }}", documentroot: "{{ wordpress_install_dir }}" }
    wordpress_installs:
      - name: wordpress
        dbname: "{{ wordpress_db_name }}"
        dbuser: "{{ wordpress_user_name }}"
        dbpass: "{{ wordpress_user_password }}"
        dbhost: localhost
        path: "{{ wordpress_install_dir }}"
        url: "{{ wordpress_fqdndomain }}"
        title: "{{ wordpress_blog_title }}"
        admin_name: "{{ wordpress_blog_admin_name }}"
        admin_email: "{{ wordpress_blog_admin_email }}"
        admin_password: "{{ wordpress_blog_admin_password }}"
        themes:
          - name: twentytwelve
            activate: true
        plugins: [ ]
        users: { }
        options: [ ]
        queries: [ ]

