---

- name: Use Ansible hostname if domain is not defined
  set_fact:
    gitlab_domain: "{{ ansible_fqdn }}"
  when: gitlab_domain == ""

- name: Copy GitLab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab