---

- name: run apt update
  shell: apt update
  when: ansible_distribution == 'Ubuntu'

- name: Install Gitlab dependencies
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - postfix

- name: Get Gitlab Repository File
  get_url: 
    url: "{{ gitlab_repo_package }}"
    dest: /tmp/{{ script_name }}

- name: Execute Gitlab Repo File
  shell: bash /tmp/{{ script_name }}

- name: Install Gitlab CE
  package:
    name: gitlab-ce
    state: present