---

- name: Update prefix table on wp-config
  ansible.builtin.lineinfile:
    path: "{{ wordpress_install_dir }}/wp-config.php"
    regexp: '^\$table_prefix = '
    line: "$table_prefix = '{{ sql_table_prefix }}';"

- name: Replace Old URL
  command: >-
    {{ wordpress_wp_cli_install_dir }}/wp-cli search-replace "{{ sql_old_url }}" "{{ wordpress_fqdndomain }}" --path="{{ wordpress_install_dir }}" --allow-root

- name: Update Blog Name
  command: >-
    {{ wordpress_wp_cli_install_dir }}/wp-cli option update blogname "{{ wordpress_blog_title }}" --path="{{ wordpress_install_dir }}" --allow-root

- name: Update Blog Description
  command: >-
    {{ wordpress_wp_cli_install_dir }}/wp-cli option update blogname "{{ wordpress_blog_description }}" --path="{{ wordpress_install_dir }}" --allow-root

- name: Update Admin Email
  command: >-
    {{ wordpress_wp_cli_install_dir }}/wp-cli option update admin_email "{{ wordpress_blog_admin_email }}" --path="{{ wordpress_install_dir }}" --allow-root

- name: Update User Credentials
  command: >-
    {{ wordpress_wp_cli_install_dir }}/wp-cli user update admin --user_pass="{{ wordpress_blog_admin_password }}" --user_email="{{ wordpress_blog_admin_email }}" --skip-email --path="{{ wordpress_install_dir }}" --allow-root