---

- name: Extracting Content
  unarchive:
    src: "portal_berita/wp-content.zip"
    dest: "{{ wordpress_install_dir }}"
    creates: "{{ wordpress_install_dir }}/wp-content/themes/jnews/index.php"
  delegate_to: localhost

- name: Recreate Database [Drop Database].
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "absent"
    target: "{{ item.target | default(omit) }}"
  with_items: "{{ mysql_databases }}"

- name: Recreate Database [Create Database].
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
    target: "{{ item.target | default(omit) }}"
  with_items: "{{ mysql_databases }}"

- name: Dump Database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: import
    target: "{{ playbook_dir }}/roles/jagoanhosting.wordpress/files/{{ wordpress_theme }}/{{ wordpress_theme }}.sql"
